name: Daily literature update

on:
  workflow_dispatch:
  schedule:
    - cron: "15 23 * * *"

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - name: Test GitHub Actions
        run: echo "GitHub Actions is working"
